//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entify.Services.Logger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entify.Services.Logger.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;[dbo].[Sp_Log]&apos;) IS NOT NULL
        ///	DROP PROC dbo.Sp_Log
        ///EXEC(
        /// &apos;CREATE PROC Sp_Log
        ///	@Op			NCHAR(50) 
        ///	,@Id		INT				= 0
        ///	,@Value		NVARCHAR(MAX)	= &apos;&apos;&apos;&apos;
        ///	,@Created	DATETIME		= NULL
        ///AS
        ///BEGIN
        ///	DECLARE @ERROR_MESSAGE  NVARCHAR(4000),
        ///			@ERROR_SEVERITY INT,
        ///			@ERROR_STATE	INT;
        ///
        ///	BEGIN TRANSACTION
        ///	BEGIN TRY
        ///
        ///		IF @Op = &apos;&apos;CREATE&apos;&apos;
        ///		BEGIN
        ///			INSERT INTO Tbl_Log ([Value],[Created]) VALUES (@Value,@Created)
        ///			
        ///			COMMIT TRANSACTION
        ///			SELECT 1
        ///			RETURN 
        ///		END
        ///
        ///		IF @Op = &apos;&apos;READ&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CREATE_SP {
            get {
                return ResourceManager.GetString("CREATE_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sysobjects WHERE name=&apos;{0}&apos; and xtype=&apos;U&apos;)
        ///BEGIN
        ///	CREATE TABLE {0}(
        ///		Id		INT				PRIMARY KEY IDENTITY,
        ///		Value	NVARCHAR(MAX),
        ///		Created DATETIME
        ///	);
        ///END.
        /// </summary>
        public static string CREATE_TABLE {
            get {
                return ResourceManager.GetString("CREATE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp_Log.
        /// </summary>
        public static string DEFAULT_PROC_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_PROC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tbl_Log.
        /// </summary>
        public static string DEFAULT_TABLE_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_TABLE_NAME", resourceCulture);
            }
        }
    }
}
