//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entify.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entify.Domain.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entify process exception, something went wrong {0}.
        /// </summary>
        public static string EntifyException {
            get {
                return ResourceManager.GetString("EntifyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataReader column that we expected has a null value and that is not right..
        /// </summary>
        public static string NullDataReaderColumnException {
            get {
                return ResourceManager.GetString("NullDataReaderColumnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given entity is null.
        /// </summary>
        public static string NullEntityException {
            get {
                return ResourceManager.GetString("NullEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} was not gotten, place check if all the Entify libraries are successful loaded.
        /// </summary>
        public static string NullMethodException {
            get {
                return ResourceManager.GetString("NullMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter o given variable is null.
        /// </summary>
        public static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataReader has more columns the expected, please check if your entity has the right structure or if your Query returns the right data..
        /// </summary>
        public static string UnexpectedDataReaderException {
            get {
                return ResourceManager.GetString("UnexpectedDataReaderException", resourceCulture);
            }
        }
    }
}
