name: Github Action Entify

on:
  push:
    branches:
      - develop

jobs: 
  build:
    strategy:
      matrix:
        configuration: [ Release ]
    
    runs-on: ubuntu-latest
    
    env:
      SOLUTION_NAME: Entify.sln                                 
      PROJECT_PATH: ./Entify/Entify.csproj
      PROJECT_PACKAGE_PATH: cd /Entify/bin
      TEST_PROJECT_PATH: ./Entify.Tests/Entify.Tests.csproj           
    
    steps:
      - name: Cloning project (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
        
      - name: Checking files
        run: ls -l

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x    
        
      - name: Checking version
        run: dotnet --version      
          
      - name: Restoring packages
        run: dotnet restore --interactive
          
      - name: Building project
        run: dotnet build --configuration $Configuration $PROJECT_PATH
        env:
          Configuration: ${{ matrix.configuration }}
          
      - name: Adding github nuget
        run: dotnet nuget add source --username sicilo --password ${{ secrets.NUGET }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/sicilo/index.json"

      - name: Packing Project
        run: dotnet pack --configuration Release $PROJECT_PATH       
          
      - name: Packing Project Result
        run: cd $PROJECT_PACKAGE_PATH        